## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [3]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [4]:

np.version.version

'1.18.1'

2. Crear un arreglo 1D con enteros positivos aleatorios

In [57]:

positivos_aleatorios = np.fromiter((np.random.randint(300) for x in range(1000)),int)
positivos_aleatorios

array([201, 275, 189,  40, 261, 200,  24,  47,  16,  99, 178, 139, 204,
         6, 168,  34, 259, 100, 195, 245,  40,  98, 101,  87, 253,  58,
       263, 175, 139, 164, 217, 296, 103, 286, 278,  69, 101,  45, 210,
        49,  28,  35, 111, 152, 231, 222, 185, 219,   5, 188, 221,  87,
       144, 299, 143, 101,  97, 261,  69,  11, 171,  98, 294,  38, 175,
        15,  53,  59, 235, 177,  11, 192, 165, 287,  67,  68, 220, 114,
       111, 193,   3, 185,  18, 262, 252,   7,  88, 191, 200, 291,  18,
         1,   0,  64, 176, 131, 153, 101,  35,  53,  68, 252, 194,  30,
         2, 206, 241, 100,  59, 282, 285,   5,   2,  50,  35,   4, 268,
       184, 105,  81, 115, 271,  97, 186, 121, 115, 273,  76, 213, 126,
       160, 280, 143,  81, 263, 244,  75, 140,  91,  22, 257, 143,  47,
        85, 224,   5,  44, 199, 266, 233,  57, 229, 275, 256, 188,  39,
       246,  69,  35, 115, 150, 131, 227,  85,  73, 238,  24, 262, 231,
        73,  39,  92,  10,  87, 176, 294, 258, 219, 112, 123, 29

3. Crear un arreglo booleano

In [121]:

array_boolean = np.array(([np.random.randint(2) for x in range(9)]), dtype=bool)
array_boolean

array([False, False, False, False, False,  True, False,  True,  True])

4. Extraer los items que sean divisibles en 3.

In [72]:
#divisibles = []
divisibles = [x for x in positivos_aleatorios if x % 3 == 0]
print (divisibles)

[201, 189, 261, 24, 99, 204, 6, 168, 195, 87, 69, 45, 210, 111, 231, 222, 219, 87, 144, 261, 69, 171, 294, 15, 177, 192, 165, 114, 111, 3, 18, 252, 291, 18, 0, 153, 252, 30, 282, 285, 105, 81, 186, 273, 213, 126, 81, 75, 57, 39, 246, 69, 150, 24, 231, 39, 87, 294, 258, 219, 123, 78, 27, 231, 267, 207, 75, 213, 81, 270, 72, 195, 108, 297, 297, 288, 153, 204, 87, 231, 51, 180, 66, 57, 54, 111, 18, 81, 144, 66, 222, 273, 204, 237, 153, 93, 237, 252, 66, 99, 171, 207, 264, 150, 255, 54, 222, 150, 54, 105, 237, 129, 42, 261, 219, 90, 276, 42, 33, 258, 126, 30, 150, 102, 63, 285, 12, 63, 159, 9, 129, 33, 291, 3, 285, 36, 114, 237, 183, 12, 201, 144, 21, 207, 156, 81, 222, 27, 258, 201, 84, 222, 78, 36, 51, 270, 186, 165, 285, 12, 87, 225, 117, 51, 159, 126, 192, 99, 198, 153, 255, 129, 9, 81, 153, 267, 270, 279, 240, 9, 123, 252, 66, 147, 189, 171, 27, 162, 69, 282, 42, 177, 99, 111, 225, 270, 174, 291, 42, 27, 282, 147, 36, 63, 189, 234, 78, 279, 177, 24, 72, 282, 15, 72, 231, 117, 135, 141

5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [122]:
array_boolean_twod = array_boolean.reshape(3,3)
array_boolean_twod

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

6. Obtén los items comunes entre dos arreglos

In [85]:
items_one = np.array([np.random.randint(10) for x in range(30)])
items_two = np.array([np.random.randint(10) for x in range(30)])
common_items = np.intersect1d(items_one,items_two)
common_items

array([0, 2, 3, 4, 5, 6, 7, 8])

7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [96]:
promedio = positivos_aleatorios.mean(dtype=int)
numeros_extraidos = np.array([x for x in positivos_aleatorios if x > promedio - 2 and x < promedio + 2])
numeros_extraidos

array([150, 151, 149, 149, 150, 150, 149, 150, 149, 151, 151, 151, 151,
       150])

8. Muestra solo 3 decimales en un vector.

In [130]:
decimales = np.array([np.round(np.random.rand(),3) for x in range(2)])
decimales
#decimales

array([0.351, 0.304])

9. Crea una atriz de 3x3 con los valores del 0 a 8

In [124]:
delunoalocho = np.array(range(0,9))
matriztresportres = delunoalocho.reshape(3,3)
matriztresportres

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [134]:
arreglo_buscarindices = np.array([1,2,0,0,4])
indices = np.array([x for x in range(len(arreglo_buscarindices)) if arreglo_buscarindices[x] != 0] )
indices

array([0, 1, 4])

11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [137]:
randomthirty = np.array([np.random.rand() for x in range(30)])
avg_randomthirty = randomthirty.mean()
avg_randomthirty

0.5678229914795168

12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [196]:
ones = np.ones((4,5),dtype=int)
ones[1:-1,1:-1] = 0
ones
#ones


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [150]:
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == np.round(3 * 0.1,1) #this is true

0.3 == 3 * 0.1
3*0.1

0.30000000000000004


14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [204]:
matrix_fourthteen =  np.diag([1,2,3,4], k=1)
matrix_fourthteen

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

15. Normaliza una matriz aleatoria de 5x5

In [210]:
random_matrix = np.array([np.random.rand() for x in range(25)]).reshape(5,5)
random_matrix = random_matrix - random_matrix.mean()
random_matrix = random_matrix / random_matrix.max()
random_matrix

array([[ 0.69303951, -0.89793877,  0.03317345, -0.83218769,  0.41446321],
       [ 0.75752603,  0.91895258,  0.24163291, -0.20500055,  1.        ],
       [ 0.48421197,  0.3122285 , -0.12071424, -0.99882722, -0.55528776],
       [ 0.33211858,  0.22250694,  0.95794709,  0.09104443, -0.60953768],
       [-1.03030297, -0.90543274, -0.27853306,  0.97289144, -0.99797396]])

# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [214]:
pd.__version__
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : 0.29.14
pytest           : 5.3.5
hypothesis       : 5.4.1
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       :

Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [4]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

dataframe_panda = pd.DataFrame(data,labels)
dataframe_panda

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [217]:
dataframe_panda.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


4. Regresa las primeras 3 filas del DataFrame

In [219]:
dataframe_panda[0:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [5]:
dataframe_panda.columns = ["Animal","Edad","Visitas","Prioridad"]
dataframe_panda

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no

6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [244]:
getdfcolandchangeit = dataframe_panda[["Animal","Edad"]]
getdfcolandchangeit.columns = ["Animal","Age"]
getdfcolandchangeit

Animal  Age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [245]:
dataframe_panda["Visitas"] > 3

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i    False
j    False
Name: Visitas, dtype: bool

8. ¿Cuáles son las filas donde la edad es NaN?

In [262]:
#print(dataframe_panda[train["Electrical"].isnull()][null_columns])
dataframe_panda[dataframe_panda["Edad"].isnull()]

Animal  Edad  Visitas Prioridad
d    dog   NaN        3       yes
h    cat   NaN        1       yes

9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [269]:
dataframe_panda[(dataframe_panda["Edad"] >=2) & (dataframe_panda["Edad"] <=4)]

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no

10. ¿Cuál es el total de todas las visitas?

In [272]:
dataframe_panda[["Visitas"]].sum()

Visitas    19
dtype: int64

12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [314]:
#dataframe_panda.groupby("Animal").groups
#dataframe_panda.groupby("Animal").count()
dataframe_panda.groupby("Animal").size()

Animal
cat      4
dog      4
snake    2
dtype: int64

13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [304]:
dataframe_panda['Prioridad'] = dataframe_panda['Prioridad'].eq('yes').mul(True)
dataframe_panda

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False

14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [311]:
print(dataframe_panda.sort_values(by=["Edad"],ascending = False))
print(dataframe_panda.sort_values(by=["Edad"],ascending = True))

  Animal  Edad  Visitas  Prioridad
i    dog   7.0        2      False
e    dog   5.0        2      False
g  snake   4.5        1      False
b    cat   3.0        3       True
j    dog   3.0        1      False
a    cat   2.5        1       True
f    cat   2.0        3      False
c  snake   0.5        2      False
d    dog   NaN        3       True
h    cat   NaN        1       True
  Animal  Edad  Visitas  Prioridad
c  snake   0.5        2      False
f    cat   2.0        3      False
a    cat   2.5        1       True
b    cat   3.0        3       True
j    dog   3.0        1      False
g  snake   4.5        1      False
e    dog   5.0        2      False
i    dog   7.0        2      False
d    dog   NaN        3       True
h    cat   NaN        1       True


15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [7]:
#mediaedad  tipodeanimal   visitas
dictionary = {}
x = 0
for groupname, group in dataframe_panda.groupby(["Animal","Visitas"]):
    current_edad = 0
    edad = group["Edad"].sum()
    #print(edad)
    dictionary[x] = {"TipoAnimal":groupname[0],"Visitas":groupname[1],"EdadPromedio":edad.mean()}
    x = x +1

panda_result = pd.DataFrame(dictionary)
panda_result

0    1    2    3    4      5      6
TipoAnimal    cat  cat  dog  dog  dog  snake  snake
Visitas         1    3    1    2    3      1      2
EdadPromedio  2.5    5    3   12    0    4.5    0.5

<# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto